"""empty message

Revision ID: 0cf9149c87ba
Revises: 5ab8e0ec0fe5
Create Date: 2020-10-01 21:37:44.855263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf9149c87ba'
down_revision = '5ab8e0ec0fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'en_route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('en_route', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
