"""empty message

Revision ID: 5ab8e0ec0fe5
Revises: 89bb41aacc5d
Create Date: 2020-10-01 21:36:45.766346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab8e0ec0fe5'
down_revision = '89bb41aacc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('on_ground', sa.Boolean(), nullable=True))
    op.add_column('flight', sa.Column('true_tracks', sa.Float(), nullable=True))
    op.drop_column('flight', 'delayed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('delayed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('flight', 'true_tracks')
    op.drop_column('flight', 'on_ground')
    # ### end Alembic commands ###
