"""empty message

Revision ID: 89bb41aacc5d
Revises: 
Create Date: 2020-09-20 18:53:17.418464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bb41aacc5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('cases_2_weeks_ago', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('new_cases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cases_2_weeks_ago', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('new_cases', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao24', sa.String(length=4), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('departing_airport_id', sa.Integer(), nullable=True),
    sa.Column('arriving_airport_id', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_arrival_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('delayed', sa.Boolean(), nullable=True),
    sa.Column('en_route', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['arriving_airport_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['departing_airport_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    op.drop_table('airport')
    op.drop_table('county')
    op.drop_table('state')
    # ### end Alembic commands ###
