"""empty message

Revision ID: 934bff66a118
Revises: 0cf9149c87ba
Create Date: 2020-10-12 20:22:04.655203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934bff66a118'
down_revision = '0cf9149c87ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airport', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('airport', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airport', 'longitude')
    op.drop_column('airport', 'latitude')
    # ### end Alembic commands ###
